"""
Django settings for pdf_automation project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

def _unset_invalid_ca_bundle_env(var_name: str) -> None:
    v = os.environ.get(var_name)
    if not v:
        return
    try:
        if not os.path.exists(v):
            os.environ.pop(var_name, None)
    except Exception:
        os.environ.pop(var_name, None)

for _k in ('REQUESTS_CA_BUNDLE', 'SSL_CERT_FILE', 'CURL_CA_BUNDLE', 'HTTPLIB2_CA_CERTS'):
    _unset_invalid_ca_bundle_env(_k)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'W0gz-iqfKukuhn92Xzi_KiV7E7552-_v98Bk12UOM5DIltqle03_0si_PwLGavtLzM0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'testserver,localhost,127.0.0.1,192.168.10.7').split(',')
    if host.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    # Custom apps
    'pdfs',
    'processing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pdf_automation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pdf_automation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv('DJANGO_MEDIA_ROOT', str(BASE_DIR / 'media')))

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google Drive Configuration
GOOGLE_DRIVE_CREDENTIALS_PATH = os.getenv('GOOGLE_DRIVE_CREDENTIALS_PATH', 'credentials/service-account-key.json')
GOOGLE_DRIVE_ROOT_FOLDER_ID = os.getenv('GOOGLE_DRIVE_ROOT_FOLDER_ID', '1pOaBjXnY07sQDDtym85KQVXr_Ept21Nd')

# File Upload Settings
# Default: 1GB (override via env UPLOAD_MAX_SIZE)
UPLOAD_MAX_SIZE = int(os.getenv('UPLOAD_MAX_SIZE', 1 * 1024 * 1024 * 1024))
DATA_UPLOAD_MAX_MEMORY_SIZE = UPLOAD_MAX_SIZE
FILE_UPLOAD_MAX_MEMORY_SIZE = UPLOAD_MAX_SIZE

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Split tuning (recommended for typical 300-output PDFs)
SPLIT_TASK_CHUNK_SIZE = int(os.getenv('SPLIT_TASK_CHUNK_SIZE', 25))

# Celery queue routing
# On Windows Server, run separate celery workers with --pool=solo per queue.
CELERY_TASK_DEFAULT_QUEUE = os.getenv('CELERY_TASK_DEFAULT_QUEUE', 'default')
CELERY_TASK_CREATE_MISSING_QUEUES = True

CELERY_TASK_ROUTES = {
    # Heavy CPU/RAM work
    'processing.tasks.preflight_split_job': {'queue': 'split'},
    'processing.tasks.split_pdf_job': {'queue': 'split'},
    'processing.tasks.split_pdf_chunk_job': {'queue': 'split'},
    'processing.tasks.finalize_split_job': {'queue': 'split'},

    # Network-bound work
    'processing.tasks.upload_split_job': {'queue': 'upload'},
}

# Backpressure (limits for concurrent running jobs)
# These protect the server from RAM spikes when many users start jobs at once.
MAX_RUNNING_JOBS_TOTAL = int(os.getenv('MAX_RUNNING_JOBS_TOTAL', 4))
MAX_RUNNING_JOBS_ASYNC = int(os.getenv('MAX_RUNNING_JOBS_ASYNC', 3))

# Authentication Settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Use unique cookie names so sessions don't collide with other local Django apps
# running on the same host (cookies are shared across ports).
SESSION_COOKIE_NAME = 'pdf_automation_sessionid'
CSRF_COOKIE_NAME = 'pdf_automation_csrftoken'

X_FRAME_OPTIONS = 'SAMEORIGIN'

