# Generated by Django 4.2.7 on 2025-12-03 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFolderCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('drive_folder_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Drive Folder Cache',
                'verbose_name_plural': 'Drive Folder Caches',
            },
        ),
        migrations.CreateModel(
            name='OriginalPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('file_path', models.FileField(upload_to='originals/%Y/%m/%d/')),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('total_pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Original PDF',
                'verbose_name_plural': 'Original PDFs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('end_page', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('local_path', models.CharField(blank=True, max_length=1000)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('drive_file_id', models.CharField(blank=True, max_length=255)),
                ('drive_webview_link', models.URLField(blank=True, max_length=500)),
                ('drive_folder_path', models.CharField(blank=True, max_length=1000)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('UPLOADED', 'Uploaded'), ('DUPLICATE', 'Duplicate'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('hospital', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_sets', to='pdfs.originalpdf')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_sets', to='pdfs.patient')),
            ],
            options={
                'verbose_name': 'PDF Set',
                'verbose_name_plural': 'PDF Sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummaryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='pdfs.patient')),
                ('pdf_sets_included', models.ManyToManyField(related_name='summaries', to='pdfs.pdfset')),
            ],
            options={
                'verbose_name': 'Summary Document',
                'verbose_name_plural': 'Summary Documents',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pdfset',
            index=models.Index(fields=['state'], name='pdfs_pdfset_state_691293_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfset',
            index=models.Index(fields=['patient', 'created_at'], name='pdfs_pdfset_patient_663ea8_idx'),
        ),
    ]
