# Generated by Django 4.2.7 on 2025-12-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfset',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pdfset',
            name='section_type',
            field=models.CharField(blank=True, default='Medical_Records', max_length=100),
        ),
    ]
