# Generated by Django 4.2.7 on 2026-01-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0002_pdfset_doctor_name_pdfset_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderStructureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default='default', max_length=100, unique=True)),
                ('structure_type', models.CharField(choices=[('FLAT', 'Flat: Root/PatientName/*.pdf'), ('WITH_SPLITS', 'With Splits: Root/PatientName/splits/*.pdf'), ('YEAR_MONTH', 'Year/Month: Root/Year/Month/PatientName/*.pdf'), ('CUSTOM', 'Custom structure')], default='FLAT', max_length=20)),
                ('root_folder_id', models.CharField(help_text='Google Drive root folder ID', max_length=255)),
                ('path_template', models.CharField(blank=True, help_text='Path template for CUSTOM type', max_length=500)),
                ('pdf_subfolder', models.CharField(blank=True, help_text="Subfolder for PDFs (e.g., 'splits') or empty", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Folder Structure Configuration',
                'verbose_name_plural': 'Folder Structure Configurations',
                'ordering': ['-is_active', 'config_name'],
            },
        ),
    ]
