# Generated by Django 4.2.7 on 2026-01-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0003_folderstructureconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_filename', models.CharField(max_length=500)),
                ('input_file', models.FileField(upload_to='processing/inputs/%Y/%m/%d/')),
                ('output_filename', models.CharField(blank=True, max_length=500)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='processing/outputs/%Y/%m/%d/')),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('folder_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('total_statements', models.IntegerField(default=0)),
                ('linked_statements', models.IntegerField(default=0)),
                ('unlinked_statements', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('user_friendly_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Processing History',
                'verbose_name_plural': 'Processing Histories',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
