# Generated by Django 5.1.15 on 2026-01-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0004_processinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('credentials_file', models.FileField(upload_to='drive_credentials/')),
                ('root_folder_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drive Profile',
                'verbose_name_plural': 'Drive Profiles',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
