# Generated by Django 5.1.15 on 2026-01-14 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0006_processinghistory_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('run_mode', models.CharField(choices=[('ASYNC', 'Async'), ('SYNC', 'Sync')], max_length=10)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('input_pdf_name', models.CharField(blank=True, max_length=500)),
                ('input_pdf_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('input_docx_name', models.CharField(blank=True, max_length=500)),
                ('input_docx_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('page_count_total', models.IntegerField(blank=True, null=True)),
                ('outputs_requested', models.IntegerField(blank=True, null=True)),
                ('total_extracted_pages', models.IntegerField(blank=True, null=True)),
                ('split_chunk_size', models.IntegerField(blank=True, null=True)),
                ('split_backend', models.CharField(blank=True, max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('processing_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='pdfs.processinghistory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('PREFLIGHT', 'Preflight'), ('SPLIT', 'Split'), ('UPLOAD', 'Upload'), ('WORD_PROCESS', 'Word Process')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.BigIntegerField(blank=True, null=True)),
                ('count_total', models.IntegerField(blank=True, null=True)),
                ('count_done', models.IntegerField(blank=True, null=True)),
                ('count_failed', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pdfs.processingrun')),
            ],
            options={
                'ordering': ['run', 'started_at'],
                'indexes': [models.Index(fields=['step', 'status'], name='pdfs_proces_step_d3ff32_idx')],
            },
        ),
    ]
